---
title: "Untitled"
output: html_document
date: "2023-12-05"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
devtools::load_all("~/Packages/AnVILWorkflow")
?AnVILBrowse
```

```{r}
AnVILBrowse("lymphoma") # 2 workspaces
```

```{r}
AnVILBrowse("lung cancer") # no result

AnVILBrowse("lung adenocarcinoma") # 10 workspaces returned
AnVILBrowse("luad") # 11 workspaces returned

AnVILBrowse("luad", "workflow") # 18 workflows returned
AnVILBrowse("luad", "data") # 10 data tables returned
```

```{r}
AnVILBrowse("female") # 38 workspaces returned
AnVILBrowse("male") # 41 workspaces returned
AnVILBrowse("gender") # 42 workspaces returned
```






```{r}
AnVILBrowse("malaria") # 5 results: search all/ return workspace

malaria_res1 <- AnVILBrowse("malaria", "workflow") # 35 results
unique(malaria_res1$workspace_key) # From 5 workspaces
dim(malaria_res1)

malaria_res2 <- AnVILBrowse("malaria", 
                            searchFrom = "workflow", 
                            returnFrom = "workspace") # 5 results: search workflow/ return workspace
dim(malaria_res2)

malaria_res3 <- AnVILBrowse("malaria", returnFrom = "workflow")
dim(malaria_res3)
```

```{r}
keyword <- "luad"
nrow(AnVILBrowse(keyword))
nrow(AnVILBrowse(keyword, "workspace"))
nrow(AnVILBrowse(keyword, "workflow"))
nrow(AnVILBrowse(keyword, "data"))

x <- AnVILBrowse(keyword, "workspace")
y <- AnVILBrowse(keyword, "workflow")
z <- AnVILBrowse(keyword, "data")

length(unique(x$workspace_key))
length(unique(y$workspace_key))
length(unique(z$workspace_key))
length(unique(c(x$workspace_key, y$workspace_key, z$workspace_key)))
```

